# Generated by Django 5.1.2 on 2025-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_delete_deparment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='about_course',
            field=models.TextField(blank=True, null=True),
        ),
    ]
