# Generated by Django 5.1.2 on 2025-02-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_group_about_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
