# Generated by Django 5.1.2 on 2025-02-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_readmore'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmore',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
