# Generated by Django 5.1.2 on 2025-02-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_readmore_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='about_course',
        ),
        migrations.RemoveField(
            model_name='group',
            name='course_info',
        ),
        migrations.AddField(
            model_name='group',
            name='read_more',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.readmore'),
        ),
    ]
