# Generated by Django 5.1.2 on 2025-02-10 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_alter_group_read_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplikes',
            name='session_id',
        ),
        migrations.AddField(
            model_name='grouplikes',
            name='user_id',
            field=models.ForeignKey(default=None, max_length=255, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
