# Generated by Django 5.1.2 on 2025-02-10 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_remove_grouplikes_session_id_grouplikes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplikes',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
